main: me.jasonhorkles.entityclearer.EntityClearer
name: EntityClearer
description: Remove entities from your worlds!
version: %VERSION%
author: JasonHorkles
website: https://github.com/SilverstoneMC/EntityClearer
api-version: 1.17
folia-supported: true
softdepend:
  - MythicMobs

commands:
  entityclearer:
    aliases: [ ecl ]
    description: "Base command for the EntityClearer plugin"
    permission: entityclearer.reload
    usage: "§cUsage: /entityclearer <debug | reload>"
  clearentities:
    description: "Clears the entities defined in the config"
    permission: entityclearer.clear

permissions:
  entityclearer.reload:
    default: op
    description: Reload the plugin
  entityclearer.debug:
    default: op
    description: Create debug dump
  entityclearer.clear:
    default: op
    description: Force clear the entities
  entityclearer.lowtps:
    default: op
    description: Notifications when the TPS is low
  entityclearer.notify:
    default: op
    description: Notifications when there are problems within the plugin
